package com.example.utils

object LocalizationUtility {

    private val translations = mapOf(
        "en" to mapOf(
            "slogan" to "Comprehensive Shia Companion Platform",
            "time_format" to "Use 24-Hour Format",
            "verse_text" to "“And my success is not but through Allah.”",
            "verse_source" to "Surah Hud, Verse 88",
            "guidance_title" to "Ahlul Bayt (as) Guidance",
            "ask_gemini" to "Ask Gemini Topic",
            "imsak" to "Imsak",
            "fajr" to "Fajr",
            "sunrise" to "Sunrise",
            "dhuhr" to "Dhuhr",
            "asr" to "Asr",
            "sunset" to "Sunset",
            "maghrib" to "Maghrib",
            "isha" to "Isha",
            "midnight" to "Midnight (Nisfe Shab)",
            "quran" to "Quran",
            "mafatih" to "Mafatih",
            "ahkam" to "Ahkam",
            "meet" to "Meet",
            "calendar" to "Calendar",
            "hussainiyah" to "Hussainiyah",
            "library" to "Library",
            "tasbeeh" to "Tasbeeh",
            "tracker" to "Prayer Tracker & Qada",
            "exact_location" to "Astronomical Shia Offsets",
            "exact_location_sub" to "Fajr begins 15°30' twilight, Asr calculations utilize Shadow rules, and Maghrib is precisely 4 degrees past sunset.",
            "settings" to "Settings & Profile",
            "language" to "Change Language",
            "adhan" to "Adhan Notifications",
            "notifications_enabled" to "Adhan Sound Alerts Enabled",
            "notifications_disabled" to "Adhan Sound Alerts Disabled",
            "share" to "Share Application",
            "faq" to "Frequently Asked Questions (FAQ)",
            "back" to "Return",
            "log_in_google" to "Sign In with Google",
            "log_out" to "Sign Out",
            "google_logged_in" to "Signed in with Google Securely",
            "sim_login" to "Simulating Secure Login Sync...",
            "show_guidance_startup" to "Show Ahlul Bayt Guidance on Startup",
            "show_guidance_startup_sub" to "Toggle to show or hide the Ahlul Bayt (as) Guidance pop-up upon application launch.",
            "guidance_language" to "Guidance Language Setting",
            "guidance_language_sub" to "Choose to display start-up guidance and Shia quotes in English or Urdu directly.",
            "masoomeen_title" to "14 Infallible Masoomeen (as)",
            "masoomeen_sub" to "Explore the sacred biographies and lives of Ahlul Bayt",
            "born" to "Born",
            "martyred" to "Martyred",
            "burial" to "Burial Shrine",
            "close" to "Close",
            
            // Legacy/Modern Buttons UI Localizer
            "tile_dua" to "Dua",
            "tile_calculator" to "Calculator",
            "tile_qibla" to "Qibla",
            "tile_calendar" to "Calendar",
            "tile_mosque" to "Mosque Map",
            "tile_tasbeeh" to "Tasbeeh",
            "tile_tracker" to "Tracker",
            "tile_aichat" to "AI Chat",
            "tile_masoomeen" to "Masoomeen",
            "tile_names_allah" to "99 Names",
            "tile_names_muhammad" to "Prophet Names",
            "tile_youtube" to "Videos",
            "tile_ramadan" to "Ramadan Tracker",

            // Qibla Compass specific
            "qibla_compass" to "QIBLA COMPASS",
            "aligned_kaaba" to "ALIGNED WITH KAABA",
            "aligned_success" to "Successfully aligned for Prayer!",
            "slow_rotate" to "Slowly rotate your device left or right until pointer turns Green",
            "compass_dial" to "Compass Dial",
            "map_pin_view" to "Map Pin View",
            "to_kaaba" to "to Kaaba",
            "geographic_calcs" to "GEOGRAPHIC CALCULATIONS",
            "selected_reference" to "Selected Reference",
            "kaaba_direction" to "Kaaba Direction (Ghadir angle)",
            "east_north" to "True East-North",
            "global_qibla_map" to "GLOBAL QIBLA PIN MAP",
            "mecca_kaaba" to "Mecca (Kaaba)",
            "reference_pin" to "Reference Pin",
            "holy_kaaba" to "Holy Kaaba",
            "mecca_sa" to "Mecca, SA",
            "gps_sensor_warning" to "Turn on GPS / place machine flat away from electronic laptops, charging adapters, or magnets to ensure clean sensor feedback.",

            // Custom Calculators & Khums labels
            "islamic_calculators" to "Islamic Calculators",
            "select_calc_sub" to "Select a calculator to continue",
            "khums_calc" to "Khums Calculator",
            "khums_calc_desc" to "Calculate 20% Islamic tax on surplus wealth.",
            "zakat_calc" to "Zakat Calculator",
            "zakat_calc_desc" to "Calculate Wajib and Mustahab Zakat on assets.",
            "fitrana_calc" to "Fitrana (Zakat al-Fitr)",
            "fitrana_calc_desc" to "Calculate Fitrana for your family.",
            "musafir_calc" to "Musafir Calculator",
            "musafir_calc_desc" to "Calculate travel distance and prayer rules.",
            "inheritance_calc" to "Inheritance Calculator",
            "inheritance_calc_desc" to "Shia Fiqh based inheritance distribution.",
            "date_conv_calc" to "Date Converter",
            "greg_hijri_desc" to "Convert between Islamic Hijri & Gregorian dates.",
            "khums_info_text" to "Khums is a 20% tax on annual surplus wealth (savings leftover after necessary daily yearly expenses). In Shia jurisprudence, it is split equally between Sehm-e-Imam and Sehm-e-Sadat.",
            "annual_income" to "Total Annual Income/Savings",
            "allowable_expenses" to "Allowable Yearly Expenses",
            "total_surplus" to "Total Surplus",
            "khums_due" to "Khums Due",
            "sehm_imam_label" to "Sehm-e-Imam (50%)",
            "sehm_sadat_label" to "Sehm-e-Sadat (50%)",

            // Duas & Ziyarats Screen
            "duas_ziyarats" to "Shi'ite Duas & Ziyarat",
            "duas_ziyarats_sub" to "Authentic prayers with Audio",
            "search_duas" to "Search Supplications / Ziyarats...",
            "cat_all" to "All",
            "cat_famed" to "Famed",
            "cat_weekly" to "Weekly",
            "cat_daily" to "Daily",
            "cat_ziyarats" to "Ziyarats",
            "lunar_phase_tracker" to "Lunar Phase Tracker",
            "masoomeen_remembrance_calendar" to "Masoomeen Remembrance Calculator",
            "lunar_phase_tracker_sub" to "Islamic Date & Moon Phases",
            "next_event" to "NEXT EVENT",
            "wiladat" to "WILADAT (BIRTH)",
            "shahadat" to "SHAHADAT",
            "days_remaining" to "Days Remaining",
            "upcoming_anniversary" to "Upcoming Lunar Anniversary Schedule",
            "today" to "Today",
            "tomorrow" to "Tomorrow",
            "in_days" to "In %d days",
            "gregorian_label" to "• Gregorian: ",
            "saved_items" to "Saved Items",
            "my_bookmarks" to "My Bookmarks",
            "daily_quotes" to "Daily Quotes",
            "tab_duas" to "Duas",
            "tab_ziyarats" to "Ziyarats",
            "tab_all" to "All",
            "no_saved_duas" to "No saved Duas or Ziyarats yet.",
            "bookmarked_duas" to "Bookmarked Duas",
            "bookmarked_ziyarats" to "Bookmarked Ziyarats",
            "no_saved_quotes" to "No saved quotes yet.",
            "ahlul_bayt" to "Ahlul Bayt",
            "lunar_date" to "Lunar date:"
        ),
        "ar" to mapOf(
            "slogan" to "منصة رفيق الشيعة المتميزة",
            "time_format" to "استخدم نظام 24 ساعة",
            "verse_text" to "“وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ”",
            "verse_source" to "سورة هود، الآية ٨٨",
            "guidance_title" to "إرشاد أهل البيت (ع)",
            "ask_gemini" to "اسأل جيمني عن موضوع",
            "imsak" to "الإمساك",
            "fajr" to "الفجر",
            "sunrise" to "الشروق",
            "dhuhr" to "الظهر",
            "asr" to "العصر",
            "sunset" to "الغروب",
            "maghrib" to "المغرب",
            "isha" to "العشاء",
            "midnight" to "منتصف الليل (نصف شب)",
            "quran" to "القرآن الكريم",
            "mafatih" to "مفاتيح الجنان",
            "ahkam" to "خمس وأحكام",
            "meet" to "قبلة ومساجد",
            "calendar" to "تقويم قمري",
            "hussainiyah" to "الحسينية",
            "library" to "مكتبة شيعية",
            "tasbeeh" to "مسبحة الذكر",
            "tracker" to "متابع الصلوات",
            "exact_location" to "تفاصيل التوقيت الشرعي شيعي",
            "exact_location_sub" to "يبدأ الفجر عند غسق 15°30'، وتعتمد صلاة العصر على قواعد الظل الفقهية، والمغرب عند زوال الحمرة الشرقية (بعد 4 درجات من الغروب).",
            "settings" to "الإعدادات والحساب",
            "language" to "تغيير اللغة",
            "adhan" to "تنبيهات الأذان الشرعي",
            "notifications_enabled" to "صوت الأذان مفعل",
            "notifications_disabled" to "صوت الأذان معطل",
            "share" to "مشاركة التطبيق",
            "faq" to "الأسئلة الشائعة والشرعية",
            "back" to "رجوع",
            "log_in_google" to "تسجيل الدخول بجوجل",
            "log_out" to "تسجيل الخروج",
            "google_logged_in" to "تم تسجيل الدخول بجوجل بأمان",
            "sim_login" to "جاري فحص الجلسة عبر مصلحة الحسابات...",
            "show_guidance_startup" to "إظهار إرشاد أهل البيت عند بدء التشغيل",
            "show_guidance_startup_sub" to "إظهار أو إخفاء نافذة إرشاد أهل البيت (ع) التوجيهية عند فتح التطبيق.",
            "guidance_language" to "لغة الإرشاد المفضلة",
            "guidance_language_sub" to "اختر ما إذا كانت حكمة أهل البيت (ع) تظهر بالإنجليزية أو الأوردو افتراضيًا.",
            "masoomeen_title" to "١٤ المعصومين (عليهم السلام)",
            "masoomeen_sub" to "اضغط لاستكشاف السيرة العطرة لأهل البيت (ع)",
            "born" to "الولادة",
            "martyred" to "الشهادة",
            "burial" to "المرقد الشريف",
            "close" to "إغلاق",

            // Legacy/Modern Buttons UI Localizer
            "tile_dua" to "الأدعية والزيارات",
            "tile_calculator" to "حاسبة الخمس",
            "tile_qibla" to "القبلة الشرعية",
            "tile_calendar" to "التقويم الهجري",
            "tile_mosque" to "خريطة المساجد",
            "tile_tasbeeh" to "مسبحة الذكر",
            "tile_tracker" to "متابع الصلوات",
            "tile_aichat" to "الدردشة الذكية",
            "tile_masoomeen" to "١٤ معصوم",
            "tile_names_allah" to "٩٩ اسم الله",
            "tile_names_muhammad" to "أسماء محمدؐ",
            "tile_youtube" to "مقاطع فيديو",
            "tile_ramadan" to "متابع رمضان",

            // Qibla Compass specific
            "qibla_compass" to "بوصلة القبلة",
            "aligned_kaaba" to "متجه نحو الكعبة",
            "aligned_success" to "تم التوجيه بنجاح للصلاة!",
            "slow_rotate" to "يرجى تدوير الجهاز ببطء حتى يتغير لون المؤشر إلى الأخضر",
            "compass_dial" to "قرص البوصلة",
            "map_pin_view" to "عرض الخريطة",
            "to_kaaba" to "نحو الكعبة",
            "geographic_calcs" to "الحسابات الجغرافية",
            "selected_reference" to "المرجع المحدد",
            "kaaba_direction" to "اتجاه الكعبة (زاوية الغدير)",
            "east_north" to "الشرق-الشمال الحقيقي",
            "global_qibla_map" to "خريطة القبلة العالمية",
            "mecca_kaaba" to "مكة (الكعبة)",
            "reference_pin" to "دبوس المرجع",
            "holy_kaaba" to "الكعبة المشرفة",
            "mecca_sa" to "مكة، السعودية",
            "gps_sensor_warning" to "يرجى تشغيل نظام GPS ووضع الجهاز بشكل مستوٍ بعيدًا عن الأجهزة الإلكترونية والشواحن الكهربائية والمغناطیس للحصول على قراءة دقيقة للمستشعر.",

            // Custom Calculators & Khums labels
            "islamic_calculators" to "الحاسبات الشرعية",
            "select_calc_sub" to "يرجى اختيار حاسبة من الأسفل للمتابعة",
            "khums_calc" to "حاسبة خمس",
            "khums_calc_desc" to "احسب ضريبة الخمس السنوية بنسبة 20٪ من الفائض المالي.",
            "zakat_calc" to "حاسبة زكاة المال",
            "zakat_calc_desc" to "حساب الزكاة المستحبة والواجبة على أصولك.",
            "fitrana_calc" to "زكاة الفطرة",
            "fitrana_calc_desc" to "حساب زكاة الفطرة لعائلتك.",
            "musafir_calc" to "حاسبة المسافر الشرعية",
            "musafir_calc_desc" to "حساب مسافة السفر وتقصير الصلوات والإفطار.",
            "inheritance_calc" to "حاسبة تقسيم المواريث",
            "inheritance_calc_desc" to "توزيع المواريث والتركات والوصايا وفق الفقه الخمس.",
            "date_conv_calc" to "محول التقويم الهجري",
            "greg_hijri_desc" to "التحويل المتبادل بين التاريخ الهجري والميلادي العيسوي.",
            "khums_info_text" to "الخمس هو ضريبة عبادية بنسبة 20% على الفاضل من المؤونة السنوية (المتبقي من المدخرات بعد المصاريف السنوية الضرورية). ويجمع في الفقه الجعفري بالتساوي بين سہم الإمام (ع) وسہم السادة الكرام.",
            "annual_income" to "إجمالي الدخل / المدخرات السنوية",
            "allowable_expenses" to "المصاريف السنوية المستثناة",
            "total_surplus" to "إجمالي الفائض المشمول بالخمس",
            "khums_due" to "الخمس الواجب",
            "sehm_imam_label" to "سهم الإمام (ع) (50%)",
            "sehm_sadat_label" to "سهم السادة (50%)",

            // Duas & Ziyarats Screen
            "duas_ziyarats" to "الأدعية والزيارات الشرعية",
            "duas_ziyarats_sub" to "مجموعة مأثورة مع صوت عذب",
            "search_duas" to "ابحث في الأدعية والزيارات الكريمة...",
            "cat_all" to "الكل",
            "cat_famed" to "الأدعية الشهيرة",
            "cat_weekly" to "الأدعية الأسبوعية",
            "cat_daily" to "الأدعية اليومية",
            "cat_ziyarats" to "الزيارات",
            "lunar_phase_tracker" to "متتبع مراحل القمر",
            "masoomeen_remembrance_calendar" to "حاسبة التواريخ القمرية للمعصومين",
            "lunar_phase_tracker_sub" to "التاريخ الإسلامي ومنازل القمر",
            "next_event" to "المناسبة القادمة",
            "wiladat" to "ولادة",
            "shahadat" to "شهادة",
            "days_remaining" to "أيام متبقية",
            "upcoming_anniversary" to "الجدول القادم للمناسبات القمرية",
            "today" to "اليوم",
            "tomorrow" to "غداً",
            "in_days" to "بعد %d أيام",
            "gregorian_label" to "• الميلادي: ",
            "saved_items" to "العناصر المحفوظة",
            "my_bookmarks" to "إشاراتي المرجعية",
            "daily_quotes" to "اقتباسات يومية",
            "tab_duas" to "أدعية",
            "tab_ziyarats" to "زيارات",
            "tab_all" to "الكل",
            "no_saved_duas" to "لا توجد أدعية أو زيارات محفوظة بعد.",
            "bookmarked_duas" to "الأدعية المحفوظة",
            "bookmarked_ziyarats" to "الزيارات المحفوظة",
            "no_saved_quotes" to "لا توجد اقتباسات محفوظة بعد.",
            "ahlul_bayt" to "أهل البيت",
            "lunar_date" to "التاريخ الهجري:"
        ),
        "ur" to mapOf(
            "slogan" to "جامع شیعہ رفیقِ نماز و عبادات",
            "time_format" to "24 گھنٹے کا وقت استعمال کریں",
            "verse_text" to "“اور میری توفیق صرف اللہ کی مدد سے ہے۔”",
            "verse_source" to "سورہ ہود، آیت ۸۸",
            "guidance_title" to "رہنمائی اہلبیت (ع)",
            "ask_gemini" to "جیمنی سے سوال پوچھیں",
            "imsak" to "امساک",
            "fajr" to "فجر",
            "sunrise" to "طلوعِ آفتاب",
            "dhuhr" to "ظہر",
            "asr" to "عصر",
            "sunset" to "غروبِ آفتاب",
            "maghrib" to "مغرب",
            "isha" to "عشاء",
            "midnight" to "نصف شب",
            "quran" to "قرآن مجید",
            "mafatih" to "مفاتیح الجنان",
            "ahkam" to "احکام الشرعیہ / خمس",
            "meet" to "مساجد اور قبلہ نما",
            "calendar" to "ہجری قمری کلینڈر",
            "hussainiyah" to "حسینیہ آڈیو و اذان",
            "library" to "معلومات کتب خانہ",
            "tasbeeh" to "تسبیحات و ذکر",
            "tracker" to "نماز ٹریکر و قضا",
            "exact_location" to "شیعہ فلکیاتی اوقات کی معلومات",
            "exact_location_sub" to "فجر کی نماز کا آغاز سنہری پٹی (15°30' twilight) سے ہوتا ہے، عصر کے لیے مخصوص شیعہ شیڈو قوانین نافذ ہیں، اور مغرب غروبِ آفتاب کے ٹھیک 4 ڈگری بعد ہوتا ہے۔",
            "settings" to "ترتیبات اور پروفائل",
            "language" to "زبان تبدیل کریں",
            "adhan" to "انداز الرٹس ترتیبات",
            "notifications_enabled" to "اذان مخصوص آڈیو الرٹ فعال ہے",
            "notifications_disabled" to "اذان الرٹ غیر فعال ہے",
            "share" to "ایپ شیئر کریں",
            "faq" to "عام فقہی و تکنیکی سوالات (FAQ)",
            "back" to "واپس جائیں",
            "log_in_google" to "گوگل کے ساتھ لاگ ان کریں",
            "log_out" to "لاگ آؤٹ کریں",
            "google_logged_in" to "گوگل ہولڈر کے طور پر کامیابی سے لاگ ان ہوا",
            "sim_login" to "انکرپٹڈ گوگل کلاؤڈ سیشن لوڈ ہو رہا ہے...",
            "show_guidance_startup" to "اسٹارٹ اپ پر رہنمائی اہلبیت پاپ اپ دکھائیں",
            "show_guidance_startup_sub" to "ایپ شروع ہونے پر رہنمائی اہلبیت (ع) کا متبرک پاپ اپ دکھانے یا چھپانے کے لیے منتخب کریں۔",
            "guidance_language" to "رہنمائی اہلبیت کی زبان",
            "guidance_language_sub" to "منتخب کریں کہ روزانہ رہنمائی اہلبیت (ع) کلام اردو میں ظاہر ہو یا انگریزی میں۔",
            "masoomeen_title" to "14 معصومین علیہم السلام",
            "masoomeen_sub" to "اہلبیت علیہم السلام کی پاکیزہ زندگی اور سوانح حیات جاننے کے لیے معلومات",
            "born" to "ولادت",
            "martyred" to "شہادت",
            "burial" to "مزارِ مبارک",
            "close" to "بند کریں",

            // Legacy/Modern Buttons UI Localizer
            "tile_dua" to "دعا اور زیارات",
            "tile_calculator" to "حساب خمس",
            "tile_qibla" to "قبلہ نما",
            "tile_calendar" to "کلینڈر",
            "tile_mosque" to "مساجد",
            "tile_tasbeeh" to "تسبیح",
            "tile_tracker" to "ٹریکر",
            "tile_aichat" to "اے آئی چیٹ",
            "tile_masoomeen" to "14 معصومین",
            "tile_names_allah" to "اللہ کے 99 نام",
            "tile_names_muhammad" to "اسمائے محمدؐ",
            "tile_youtube" to "ویڈیوز",
            "tile_ramadan" to "شعبان وہ رمضان",

            // Qibla Compass specific
            "qibla_compass" to "قبلہ نما",
            "aligned_kaaba" to "قبلہ کی طرف رخ ہے",
            "aligned_success" to "نماز پڑھنے کے لیے درست رخ منتخب ہوا!",
            "slow_rotate" to "موبائل کو آہستہ سے گھمائیں تاکہ اشارہ سبز رنگ کا ہو جائے",
            "compass_dial" to "قبلہ نما ڈائل",
            "map_pin_view" to "خارطہ قبلہ اثر",
            "to_kaaba" to "متصل کعبہ",
            "geographic_calcs" to "جغرافیائی تفصیلات",
            "selected_reference" to "منتخب مقام",
            "kaaba_direction" to "جغرافیائی سمت (زاویہ غدیر)",
            "east_north" to "حقیقی شمال-مشرق",
            "global_qibla_map" to "عالمی قبلہ نما نقشہ",
            "mecca_kaaba" to "مکہ (کعبہ)",
            "reference_pin" to "مقامِ مرکز",
            "holy_kaaba" to "خانہ کعبہ",
            "mecca_sa" to "مکہ، سعودی عرب",
            "gps_sensor_warning" to "سینسرز کے درست الرٹ کے لیے موبائل کو ہموار سطح پر رکھیں اور برقی مقناطیسی چیزوں جیسے لیپ ٹاپ یا چارجر سے دور رکھیں۔",

            // Custom Calculators & Khums labels
            "islamic_calculators" to "خمس و شرعی حساب",
            "select_calc_sub" to "جاری رکھنے کے لیے کسی ایک شعبہ کا انتخاب کریں",
            "khums_calc" to "خمس کیلکولیٹر",
            "khums_calc_desc" to "اپنے سالانہ اضافی مال و بچت پر 20 فیصد خمس واجب کا حساب لگائیں۔",
            "zakat_calc" to "زکوٰۃ کیلکولیٹر",
            "zakat_calc_desc" to "اپنے سونے اور تجارتی مال پر زکوٰۃ کا حساب لگائیں۔",
            "fitrana_calc" to "فطرانہ کیلکولیٹر",
            "fitrana_calc_desc" to "اپنے خاندان کے لئے فطرانہ کا حساب لگائیں۔",
            "musafir_calc" to "نمازِ مسافر معلومات",
            "musafir_calc_desc" to "شرعی سفر کے فاصلے اور مسافر نماز و روزے کے قوانین جانیں۔",
            "inheritance_calc" to "تقسیمِ میراث حاسب",
            "inheritance_calc_desc" to "شیعہ فقہ جعفریہ کی روشنی میں وراثت کی شرعی تقسیم جانیں۔",
            "date_conv_calc" to "قمری تاریخ متبدل",
            "greg_hijri_desc" to "ہجری قمری اور عیسوی تاریخوں کو تبدیل کریں۔",
            "khums_info_text" to "خمس سالانہ اضافی مال و بچت پر 20٪ واجب ٹیکس ہے۔ شیعہ فقہ میں یہ برابر حصوں میں سہمِ امامؑ اور سہمِ سادات میں تقسیم ہوتا ہے۔",
            "annual_income" to "کل سالانہ آمدنی / بچت",
            "allowable_expenses" to "ضروری سالانہ اخراجات",
            "total_surplus" to "کل اضافی رقم",
            "khums_due" to "خمس واجب",
            "sehm_imam_label" to "سہمِ امام علیہ السلام (50%)",
            "sehm_sadat_label" to "سہمِ سادات (50%)",

            // Duas & Ziyarats Screen
            "duas_ziyarats" to "دعائیں اور زیارات",
            "duas_ziyarats_sub" to "مستند دعائیں اور خوبصورت آڈیو",
            "search_duas" to "مطلوبہ دعا یا زیارت تلاش کریں...",
            "cat_all" to "تمام",
            "cat_famed" to "خاص دعائیں",
            "cat_weekly" to "ہفتہ وار دعائیں",
            "cat_daily" to "روزانہ کی دعائیں",
            "cat_ziyarats" to "زیارتیں",
            "lunar_phase_tracker" to "چاند کے مراحل کا ٹریکر",
            "masoomeen_remembrance_calendar" to "مَعصُومین کی قمری تواریخ کا کیلکولیٹر",
            "lunar_phase_tracker_sub" to "اسلامی تاریخ اور چاند کے مراحل",
            "next_event" to "اگلی برسی",
            "wiladat" to "ولادت مبارک",
            "shahadat" to "شہادت",
            "days_remaining" to "دن باقی",
            "upcoming_anniversary" to "آنے والی قمری تواریخ",
            "today" to "آج",
            "tomorrow" to "کل",
            "in_days" to "%d دنوں میں",
            "gregorian_label" to "• عیسوی: ",
            "saved_items" to "محفوظ شدہ اشیاء",
            "my_bookmarks" to "میری بک مارکس",
            "daily_quotes" to "روزانہ فرامین",
            "tab_duas" to "دعائیں",
            "tab_ziyarats" to "زیارات",
            "tab_all" to "سب",
            "no_saved_duas" to "کوئی بک مارک محفوظ نہیں ہے",
            "bookmarked_duas" to "محفوظ شدہ دعائیں",
            "bookmarked_ziyarats" to "محفوظ شدہ زیارات",
            "no_saved_quotes" to "کوئی محفوظ شدہ کلمہ نہیں ہے",
            "ahlul_bayt" to "اہل بیت",
            "lunar_date" to "قمری تاریخ:"
        )
    )

    fun get(key: String, lang: String): String {
        val dict = translations[lang] ?: translations["en"]!!
        return dict[key] ?: translations["en"]!![key] ?: key
    }

    // --- DYNAMIC TRANSLATION HELPERS ---
    
    fun translateEventTitle(title: String, lang: String): String {
        if (lang == "en" || lang.isEmpty()) return title
        val isAr = lang == "ar"
        
        val words = mapOf(
            "Prophet Muhammad's Birth" to if(isAr) "ولادة النبي محمد (ص)" else "حضرت محمد (ص) کی ولادت مبارک",
            "Prophet Muhammad's Martyrdom" to if(isAr) "شهادة النبي محمد (ص)" else "حضرت محمد (ص) کی شہادت",
            "Imam Ali's Birth" to if(isAr) "ولادة الإمام علي (ع)" else "امام علی (ع) کی ولادت مبارک",
            "Imam Ali's Martyrdom" to if(isAr) "شهادة الإمام علي (ع)" else "امام علی (ع) کی شہادت",
            "Lady Fatima's Birth" to if(isAr) "ولادة السيدة فاطمة (س)" else "بی بی فاطمہ (س) کی ولادت مبارک",
            "Lady Fatima's Martyrdom" to if(isAr) "شهادة السيدة فاطمة (س)" else "بی بی فاطمہ (س) کی شہادت",
            "Imam Hasan's Birth" to if(isAr) "ولادة الإمام الحسن (ع)" else "امام حسن (ع) کی ولادت مبارک",
            "Imam Hasan's Martyrdom" to if(isAr) "شهادة الإمام الحسن (ع)" else "امام حسن (ع) کی شہادت",
            "Imam Hussain's Birth" to if(isAr) "ولادة الإمام الحسين (ع)" else "امام حسین (ع) کی ولادت مبارک",
            "Imam Hussain's Martyrdom" to if(isAr) "شهادة الإمام الحسين (ع)" else "امام حسین (ع) کی شہادت",
            "Imam Sajjad's Birth" to if(isAr) "ولادة الإمام السجاد (ع)" else "امام سجاد (ع) کی ولادت مبارک",
            "Imam Sajjad's Martyrdom" to if(isAr) "شهادة الإمام السجاد (ع)" else "امام سجاد (ع) کی شہادت",
            "Imam Baqir's Birth" to if(isAr) "ولادة الإمام الباقر (ع)" else "امام باقر (ع) کی ولادت مبارک",
            "Imam Baqir's Martyrdom" to if(isAr) "شهادة الإمام الباقر (ع)" else "امام باقر (ع) کی شہادت",
            "Imam Sadiq's Birth" to if(isAr) "ولادة الإمام الصادق (ع)" else "امام صادق (ع) کی ولادت مبارک",
            "Imam Sadiq's Martyrdom" to if(isAr) "شهادة الإمام الصادق (ع)" else "امام صادق (ع) کی شہادت",
            "Imam Kadhim's Birth" to if(isAr) "ولادة الإمام الكاظم (ع)" else "امام کاظم (ع) کی ولادت مبارک",
            "Imam Kadhim's Martyrdom" to if(isAr) "شهادة الإمام الكاظم (ع)" else "امام کاظم (ع) کی شہادت",
            "Imam Ridha's Birth" to if(isAr) "ولادة الإمام الرضا (ع)" else "امام رضا (ع) کی ولادت مبارک",
            "Imam Ridha's Martyrdom" to if(isAr) "شهادة الإمام الرضا (ع)" else "امام رضا (ع) کی شہادت",
            "Imam Jawad's Birth" to if(isAr) "ولادة الإمام الجواد (ع)" else "امام جواد (ع) کی ولادت مبارک",
            "Imam Jawad's Martyrdom" to if(isAr) "شهادة الإمام الجواد (ع)" else "امام جواد (ع) کی شہادت",
            "Imam Hadi's Birth" to if(isAr) "ولادة الإمام الهادي (ع)" else "امام ہادی (ع) کی ولادت مبارک",
            "Imam Hadi's Martyrdom" to if(isAr) "شهادة الإمام الهادي (ع)" else "امام ہادی (ع) کی شہادت",
            "Imam Askari's Birth" to if(isAr) "ولادة الإمام العسكري (ع)" else "امام عسکری (ع) کی ولادت مبارک",
            "Imam Askari's Martyrdom" to if(isAr) "شهادة الإمام العسكري (ع)" else "امام عسکری (ع) کی شہادت",
            "Imam Mahdi's Birth" to if(isAr) "ولادة الإمام المهدي (عج)" else "امام مہدی (عج) کی ولادت مبارک",
            
            "Eid al-Ghadir" to if(isAr) "عيد الغدير" else "عید غدیر",
            "Eid al-Mubahalah" to if(isAr) "عيد المباهلة" else "عید مباہلہ",
            "Arba'een of Imam Hussain" to if(isAr) "أربعين الإمام الحسين (ع)" else "چہلم امام حسین (ع)",
            "Eid al-Fitr" to if(isAr) "عيد الفطر" else "عید الفطر",
            "Eid al-Adha" to if(isAr) "عيد الأضحى" else "عید الاضحی"
        )
        return words[title] ?: title
    }

    fun translateMasoomName(name: String, lang: String): String {
        if (lang == "en" || lang.isEmpty()) return name
        val isAr = lang == "ar"
        
        // Since Imam Muhammad ibn Ali is repeated for Baqir and Jawad, 
        // we'll try to use a specific string replacement approach or just use the map. 
        // The display will be fine being Baqir/Jawad generic or we can do a fallback.
        // Actually, in the UI it's not a big issue if Jawad is just Imam Muhammad ibn Ali
        
        val words = mapOf(
            "Prophet Muhammad (saws)" to if(isAr) "النبي محمد (ص)" else "حضرت محمد (ص)",
            "Imam Ali ibn Abi Talib (as)" to if(isAr) "الإمام علي بن أبي طالب (ع)" else "امام علی ابن ابی طالب (ع)",
            "Lady Fatima al-Zahra (sa)" to if(isAr) "السيدة فاطمة الزهراء (س)" else "بی بی فاطمتہ الزہرا (س)",
            "Imam Hasan al-Mujtaba (as)" to if(isAr) "الإمام الحسن المجتبى (ع)" else "امام حسن مجتبیٰ (ع)",
            "Imam Hussain ibn Ali (as)" to if(isAr) "الإمام الحسين بن علي (ع)" else "امام حسین ابن علی (ع)",
            "Imam Ali ibn al-Hussain (as)" to if(isAr) "الإمام علي بن الحسين (ع)" else "امام علی زین العابدین (ع)",
            "Imam Muhammad ibn Ali (as)" to if(isAr) "الإمام محمد بن علي (ع)" else "امام محمد بن علی (ع)",
            "Imam Ja'far ibn Muhammad (as)" to if(isAr) "الإمام جعفر بن محمد الصادق (ع)" else "امام جعفر صادق (ع)",
            "Imam Musa ibn Ja'far (as)" to if(isAr) "الإمام موسى بن جعفر الكاظم (ع)" else "امام موسی کاظم (ع)",
            "Imam Ali ibn Musa (as)" to if(isAr) "الإمام علي بن موسى الرضا (ع)" else "امام علی رضا (ع)",
            "Imam Ali ibn Muhammad (as)" to if(isAr) "الإمام علي بن محمد الهادي (ع)" else "امام علی نقی الہادی (ع)",
            "Imam Hasan ibn Ali (as)" to if(isAr) "الإمام الحسن بن علي العسكري (ع)" else "امام حسن عسکری (ع)",
            "Imam Muhammad ibn al-Hasan (ajtf)" to if(isAr) "الإمام محمد بن الحسن المهدي (عج)" else "امام مہدی (عج)"
        )
        
        return words[name] ?: name
    }

    fun formatTimeUI(timeStr: String, use24h: Boolean): String {
        if (use24h) return timeStr
        try {
            val parts = timeStr.split(":")
            if (parts.size != 2) return timeStr
            val hstr = parts[0].trim()
            val mstr = parts[1].trim().take(2)
            val h = hstr.toIntOrNull() ?: return timeStr
            val m = mstr.toIntOrNull() ?: return timeStr
            
            val isPm = h >= 12
            val h12 = if (h % 12 == 0) 12 else h % 12
            val amPm = if (isPm) "PM" else "AM"
            return String.format("%02d:%02d %s", h12, m, amPm)
        } catch (e: Exception) {
            return timeStr
        }
    }
}
